<?php 
 include ('header.php');
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Terms and Conditions</title>
    <link rel="stylesheet" href="css/style.css">
    <!-- Bootstrap 5 CDN -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Libre+Baskerville:wght@400;700&display=swap" rel="stylesheet">
</head>
<style>
body {
    position: relative;
    margin: 0;
    padding: 0;
}

body::before {
    content: "";
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background: url('../assets/bg-image.png') no-repeat center center fixed;
    background-size: cover;
    opacity: 0.5; /* Adjust opacity */
    z-index: -1; /* Keeps it behind the content */
}


</style>
<body>
        <!-- ============================================================== -->
        <div class=" ">
            <div class="container mt-5 mb-5 terms-background">
                <div class="row">
                    <h5 class="terms-title">Terms and Conditions</h5>
                    <p class="terms-helptext">FINPLOY TERMS AND CONDITIONS</p>
    <!-- ============================================================== -->
                <div class="terms-description">
                    1. AGREED TERMS Your attention is particularly drawn to the provisions of clause 13 (Limitation of liability). About us Company details. Finploy Finance Employment (hereinbelow "Finploy") is an entity registered in India and our registered office is at 55,47, Gokul, Gandhinagar, MIG Club, Bandra East, Mumbai, Maharashtra, India. We operate the website www.finploy.in (Site). Contacting us. To contact us, telephone our customer service team at +91 81694 49669 or email us at finploy1@gmail.com. How to give us formal notice of any matter under the Contract is set out in clause 18.2.
                    </br></br>
                    2. Our contract with you Our contract. These terms and conditions (Terms) apply to the order by you and supply of Products or Services by us to you (Contract). They apply to the exclusion of any other terms that you seek to impose or incorporate, or which are implied by law, trade custom, practice or course of dealing. Entire agreement. The Contract is the entire agreement between you and us in relation to its subject matter. You acknowledge that you have not relied on any statement, promise or representation or assurance or warranty that is not set out in the Contract. Any contractual terms provided to us by you are not incorporated into the Contract in whole or in part. Language. These Terms and the Contract are made only in the English language. Your copy. You should print off a copy of these Terms or save them to your computer for future reference.
                    </br></br>
                    3. Placing an order and its acceptance Placing your order. Where an order is placed using our Site, please follow the onscreen prompts to place your order. You may only submit an order using the method set out on the site. Each order is an offer by you to buy the services specified in the order (Products or Services) subject to these Terms. Correcting input errors. Our order process allows you to check and amend any errors before submitting your order to us. Please check the order carefully before confirming it. You are responsible for ensuring that your order and any specification submitted by you is complete and accurate. Acknowledging receipt of your order. After you place your order, you will receive an email from us acknowledging that we have received it, but please note that this does not mean that your order has been accepted. Our acceptance of your order will take place as described in clause 3.4. Accepting your order. Our acceptance of your order takes place when we send an email to you to accept it (Order Confirmation), at which point and on which date (Commencement Date) the Contract between you and us will come into existence. The Contract will relate only to those Products or Services confirmed in the Order Confirmation. If we cannot accept your order. If we are unable to supply you with the Products or Services for any reason, we will inform you of this by email and we will not process your order. If you have already paid for the Products or Services, we will refund you the full amount.
                    </br></br>
                    4. Our products and services Descriptions and illustrations. It is important that the product or service that you are purchasing is made clear in the order. This may include: Job posting service; CV database access; Site advertising/advertorial; Social media target campaigns; Sourcing services; Matched searches; Virtual careers fairs; Pay for performance events; Pay for hire; Leaderboard. Any descriptions or illustrations on our Site are published for the sole purpose of giving an approximate idea of the products and services described in them. They will not form part of the Contract or have any contractual force. Changes to specification. We reserve the right to amend the specification of the Products or Services if required by any applicable statutory or regulatory requirement or if the amendment will not materially affect the nature or quality of the Products or Services. Reasonable care and skill. We warrant to you that the Products or Services will be provided using reasonable care and skill. Time for performance. We will use reasonable endeavours to meet any performance dates specified in the Order Confirmation, but any such dates are estimates only and failure to perform or provide the Products or Services by such dates will not give you the right to terminate the Contract.
                    </br></br>
                    5. Your obligations It is your responsibility to ensure that: the terms of your order are complete and accurate; you cooperate with us in all matters relating to the Products or Services; you provide us with such information and materials we may reasonably require in order to supply the Products or Services, and ensure that such information is complete and accurate in all material respects; you obtain and maintain all necessary licences, permissions and consents which may be required for the Products or Services before the date on which the Products or Services are to start; you comply with all applicable laws; your client profile is completed and maintained by a senior and appropriate member of your staff; you comply in all material respects with our Website Terms and Conditions, the terms of which are incorporated into this Contract; Where applicable, you undertake such due diligence as you consider appropriate prior to making any appointment. You acknowledge and agree that we do not vet, verify or otherwise enquire as to the accuracy of candidate information provided to us, save where you use our Products and Services under clause 4.1(e) above. If our ability to perform the Products or Services is prevented or delayed by any failure by you to fulfil any obligation listed in clause 5.1: we will be entitled to suspend performance or delivery of the Products or Services until you remedy Your Default, and to rely on Your Default to relieve us from the performance or delivery of the Products or Services, in each case to the extent Your Default prevents or delays performance or delivery of the Products or Services. In certain circumstances Your Default may entitle us to terminate the Contract under clause 12 (Termination); we will not be responsible for any costs or losses you sustain or incur arising directly or indirectly from our failure or delay to perform or deliver the Products or Services; and it will be your responsibility to reimburse us on written demand for any costs or losses we sustain or incur arising directly or indirectly from Your Default.
                    </br></br>
                    6. Charges In consideration of us providing the Products or Services you must pay our charges (Charges) in accordance with this clause 6. The Charges are the prices quoted on our Site or otherwise to you at the time you submit your order. If you wish to change the scope of the Products or Services after we accept your order, and we agree to such change, we will modify the Charges accordingly. We reserve the right to increase the Charges on an annual basis with effect from each anniversary of the Commencement Date by up to 10% and the first such increase shall take effect on the first anniversary of the Commencement Date. Any increase pursuant to this clause 6.4 is in addition to any increase in the Charges resulting from an expiry or withdrawal of any introductory, discounted or promotional rate. Our Charges are exclusive of VAT. Where VAT is payable in respect of some or all of the Products or Services you must pay us such additional amounts in respect of VAT, at the applicable rate, at the same time as you pay the Charges.
                    </br></br>
                    7. Invoicing and Payment Invoicing of and payment for the Products or Services is as agreed in the order and is usually monthly in advance, unless credit arrangements are agreed with you prior to our acceptance of the order. You may be able to pay for the Products or Services using a debit card or credit card. If you fail to make a payment under the Contract by the due date, then, without limiting our remedies under clause 12 (Termination): We shall be entitled to charge interest on the overdue sum from the due date until payment of the overdue sum, whether before or after judgment, as well as any costs incurred in collection of the overdue sum. Interest under this clause 7.3 will accrue each day at 4% a year above the Bank of England's base rate from time to time, but at 4% a year for any period when that base rate is below 0%; We shall be entitled to withdraw any credit facility extended to you; and/or Withdraw any discounts afforded to you. We shall each pay all amounts due under the Contract in full without any set-off, counterclaim, deduction or withholding (other than any deduction or withholding of tax as required by law).
                    </br></br>
                    8. Intellectual property rights All intellectual property rights in or arising out of or in connection with the Products or Services (other than intellectual property rights in any materials provided by you) will be owned by us. You agree to grant us a fully paid-up, non-exclusive, royalty-free, non-transferable licence to copy and modify any materials provided by you to us for the term of the Contract and for a period of 2 years thereafter.
                    </br></br>
                    9. How we may use your personal information We will use any personal information you provide to us to: provide the Products or Services; process your payment for the Products or Services; and inform you about similar products or services that we provide, but you may stop receiving these at any time by contacting us. We will process your personal information in accordance with our Privacy Policy the terms of which are incorporated into this Contract.
                    </br></br>
                    10. Limitation of liability We have obtained insurance cover in respect of our own legal liability for individual claims not exceeding £100,000 per claim. The limits and exclusions in this clause reflect the insurance cover we have been able to arrange and you are responsible for making your own arrangements for the insurance of any excess loss. Nothing in the Contract limits any liability which cannot legally be limited, including liability for: death or personal injury caused by negligence; fraud or fraudulent misrepresentation; and breach of the terms implied by section 2 of the Supply of Goods and Services Act 1982 (title and quiet possession). Subject to clause 10.2, we will not be liable to you, whether in contract, tort (including negligence), for breach of statutory duty, or otherwise, arising under or in connection with the Contract for: loss of profits; loss of sales or business; loss of agreements or contracts; loss of anticipated savings; loss of use or corruption of software, data or information; loss of or damage to goodwill; any indirect or consequential loss; loss arising from linked websites; loss arising from breach of our Acceptable Use Policy and/or Website Terms and Conditions. loss arising from material uploaded to our Site; and loss arising from comments or advice provided by third parties at virtual careers fairs. Subject to clause 10.2, our total liability to you arising under or in connection with the Contract, whether in contract, tort (including negligence), breach of statutory duty, or otherwise, will be limited to 100% of the total Charges paid under the Contract. To the extent relevant, the terms implied by sections 3, 4 and 5 of the Supply of Goods and Products or Services Act 1982 are, to the fullest extent permitted by law, excluded from the Contract. Unless you notify us that you intend to make a claim in respect of an event within the notice period, we shall have no liability for that event. The notice period for an event shall start on the day on which you became, or ought reasonably to have become, aware of the event having occurred and shall expire 6 months from that date. The notice must be in writing and must identify the event and the grounds for the claim in reasonable detail. Nothing in these Terms limits or affects the exclusions and limitations set out in our Website Terms and Conditions. This clause 10 will survive termination of the Contract.
                    </br></br>
                    11. Confidentiality We each undertake that we will not at any time during the Contract, and for a period of two years after its termination, disclose to any person any confidential information concerning one another's business, affairs, customers, clients or suppliers, except as permitted by clause 11.2. We each may disclose the other's confidential information: to such of our respective employees, officers, representatives, subcontractors or advisers who need to know such information for the purposes of exercising our respective rights or carrying out our respective obligations under the Contract. We will each ensure that such employees, officers, representatives, subcontractors or advisers comply with this clause 11; and as may be required by law, a court of competent jurisdiction or any governmental or regulatory authority. Each of us may only use the other's confidential information for the purpose of fulfilling our respective obligations under the Contract.
                    </br></br>
                    12. Term and Termination Our contracts are of a fixed duration and are not terminable prior to the expiry of that fixed term. Contracts with a duration of 6 months or greater shall renew automatically for the same contract period up to a maximum of 12 months unless you give us notice of cancellation in writing not less than 45 days prior to any renewal date. In the event that you wish us to cease providing the Products or Services prior to the expiry of any fixed term period, you will pay to us a sum equal to the amount which remains un-invoiced, unpaid or otherwise outstanding up until the end of the fixed term period. Without limiting any of our other rights, we may suspend the performance or delivery of the Products or Services, or terminate the Contract with immediate effect by giving written notice to you if: you commit a material breach of any term of the Contract and (if such a breach is remediable) fail to remedy that breach within 28 days of you being notified in writing to do so; you fail to pay any amount due under the Contract on the due date for payment; you take any step or action in connection with you entering administration, provisional liquidation or any composition or arrangement with your creditors (other than in relation to a solvent restructuring), applying to court for or obtaining a moratorium under Part A1 of the Insolvency Act 1986, being wound up (whether voluntarily or by order of the court, unless for the purpose of a solvent restructuring), having a receiver appointed to any of your assets or ceasing to carry on business or, if the step or action is taken in another jurisdiction, in connection with any analogous procedure in the relevant jurisdiction; you suspend, threaten to suspend, cease or threaten to cease to carry on all or a substantial part of your business; or your financial position deteriorates to such an extent that in our opinion your capability to adequately fulfil your obligations under the Contract has been placed in jeopardy. Survival. Any provision of the Contract that expressly or by implication is intended to come into or continue in force on or after termination will remain in full force and effect.
                    </br></br>
                    13. Personal Data We shall handle any personal data shared with us in compliance with our Privacy Policy and in accordance with data protection laws applicable to the jurisdiction concerned, including the Data Protection Act 2018 and General Data Protection Regulation (GDPR) 2016/679.
                    </br></br>
                    14. Events outside our control We will not be liable or responsible for any failure to perform, or delay in performance of, any of our obligations under the Contract that is caused by any act or event beyond our reasonable control (Event Outside Our Control). If an Event Outside Our Control takes place that affects the performance of our obligations under the Contract: we will contact you as soon as reasonably possible to notify you; and our obligations under the Contract will be suspended and the time for performance of our obligations will be extended for the duration of the Event Outside Our Control. We will arrange a new date for performance of the Products or Services with you after the Event Outside Our Control is over. You may cancel the Contract affected by an Event Outside Our Control [which has continued for more than 60] days. To cancel please contact us. If you opt to cancel we will refund the price you have paid, less the charges reasonably and actually incurred us by in performing the Products or Services up to the date of the occurrence of the Event Outside Our Control.
                    </br></br>
                    15. Non-solicitation You must not attempt to procure services that are competitive with the Products or Services from any of our directors, employees or consultants, whether as an employee or on a freelance basis, during the period that we are providing the Products or Services to you and for a period of six months following termination of the Contract.
                    </br></br>
                    16. Anti-Bribery and Anti-Corruption We shall during the term of this agreement: comply with all applicable laws, statutes, regulations relating to anti-bribery and anti-corruption; not engage in any activity, practice or conduct which would constitute an offence if such activity, practice or conduct had been carried out in the India; comply, where reasonable to do so, with the Yours Ethics, Anti-bribery and Anti-corruption Policies in each case as You may update them from time to time and provide them to us (Relevant Policies); maintain and enforce our own policies and procedures, including adequate procedures , to ensure compliance with the Relevant Requirements and clause 16.1(b); notify You (in writing) if we become aware of any breach of clause 16.1(a) or 16.1(b), or have reason to believe that we have received a request or demand for any undue financial or other advantage in connection with the performance of this agreement; We shall ensure that any of our agents, consultants, contractors, subcontractors or other persons engaged in performance of the our obligations under this agreement do so only on the basis of a written contract which imposes on and secures from such person terms equivalent to those imposed on us in this clause 16 (Relevant Terms). We shall be responsible for the observance and performance by such persons of the Relevant Terms, and shall be directly liable to you for any breach by such persons of any of the Relevant Terms. For the purpose of this clause 16, the meaning of adequate procedures and foreign public official and whether a person is associated with another person shall be determined in accordance with section 7(2) of the Bribery Act 2010 (and any guidance issued under section 9 of that Act), sections 6(5) and 6(6) of that Act and section 8 of that Act respectively. Breach of this clause 16 shall be deemed a material breach of this agreement.
                    </br></br>
                    17. Anti-slavery and human trafficking In performing our obligations under the agreement, we shall: comply with all applicable anti-slavery and human trafficking laws, statutes, regulations from time to time in force (Anti-Slavery Laws) including the Modern Slavery Act 2015; not engage in any activity, practice or conduct that would constitute an offence under sections 1, 2 or 4 of the Modern Slavery Act 2015 if such activity, practice or conduct had been carried out in England and Wales; and include in contracts with our subcontractors anti-slavery and human trafficking provisions that are at least as onerous as those set out in this clause 17. We represent and warrant that we have not been convicted of any offence involving slavery and human trafficking or been the subject of any investigation, inquiry or enforcement proceedings regarding any offence or alleged offence of or in connection with slavery and human trafficking. Breach of this clause 17 shall be deemed a material breach of this agreement.
                    </br></br>
                    18. Communications between us When we refer to "in writing" in these Terms, this includes email. Any notice or other communication given by one of us to the other under or in connection with the Contract must be in writing and be delivered personally, sent by pre-paid first class post or other next working day delivery service, or email. A notice or other communication is deemed to have been received: if delivered personally, on signature of a delivery receipt or at the time the notice is left at the proper address; if sent by pre-paid first class post or other next working day delivery service, at [9.00 am] on the [second] working day after posting; or if sent by email, at 9.00 am (at the local time of the recipient) the next working day after transmission. In proving the service of any notice, it will be sufficient to prove, in the case of a letter, that such letter was properly addressed, stamped and placed in the post and, in the case of an email, that such email was sent to the specified email address of the addressee. The provisions of this clause will not apply to the service of any proceedings or other documents in any legal action.
                    </br></br>
                    19. General Assignment and transfer We may assign or transfer our rights and obligations under the Contract to another entity but will always notify you in writing or by posting on this webpage if this happens. A change of control shall not, for the avoidance of doubt, be deemed as notifiable under this clause; You may only assign or transfer your rights or your obligations under the Contract to another person if we agree in writing. Variation. Any variation of the Contract only has effect if it is in writing and signed by you and us (or our respective authorised representatives). Waiver. If we do not insist that you perform any of your obligations under the Contract, or if we do not enforce our rights against you, or if we delay in doing so, that will not mean that we have waived our rights against you or that you do not have to comply with those obligations. If we do waive any rights, we will only do so in writing, and that will not mean that we will automatically waive any right related to any later default by you. Severance. Each paragraph of these Terms operates separately. If any court or relevant authority decides that any of them is unlawful or unenforceable, the remaining paragraphs will remain in full force and effect. Third party rights. The Contract is between you and us. No other person has any rights to enforce any of its terms. Governing law and jurisdiction. The Contract is governed by English law and we each irrevocably agree to submit all disputes arising out of or in connection with the Contract to the exclusive jurisdiction of the English courts.
                </div>
                
                </div>
            </div>
        </div>
</body>
            <!-- ============================================================== -->
            <!-- footer -->
            <!-- ============================================================== -->
<?php 
    include ('footer.php');
?>
